const medicineOptions = [
    { label: "TAB NIMIK P (Nimesulide and Paracetamol)", value: "TAB NIMIK P" },
    { label: "TAB ACMIK P (Aceclofenac and Paracetamol)", value: "TAB ACMIK P" },
    { label: "TAB ACMIK T (Aceclofenac,Paracetamol, trypsin chymotrypsin)", value: "TAB ACMIK T" },
    { label: "TAB DYMIK S (diclofenac potassium serratiopeptidase)", value: "TAB DYMIK S" },
    { label: "TAB STILGESIC SP (aceclofenac and paracetamol, serratiopeptidase)", value: "TAB STILGESIC SP" },
    { label: "TAB Fillace TH (aceclofenac and thiocolchicoside)", value: "TAB Fillace TH" },
    { label: "TAB Etoscot 90 (Etoricoxib 90mg)", value: "TAB Etoscot 90" },
    { label: "TAB Aquadef-6 (Deflazacort)", value: "TAB Aquadef-6" },
    { label: "TAB panmik 40 (pantaprazol 40mg)", value: "TAB panmik 40" },
    { label: "CAP Rabipil DSR (rabeprazole)", value: "CAP Rabipil DSR" },
    { label: "CAP Omiscot-D (Omeprazol and Domperidone)", value: "CAP Omiscot-D" },
    { label: "TAB Montihill-L (montelukast and levocetirizine)", value: "TAB Montihill-L" },
    { label: "TAB Nymtoss-Cold (Nimesulide+Cetirizine+Phenylephrine Hcl+caffeine)", value: "TAB Nymtoss-Cold" },
    { label: "Softgel supplerich (calcitrol calcium and vitaminD3)", value: "Softgel supplerich" },
    { label: "TAB Aquacef-LB (Cifixim200 latic acid bacillus)", value: "TAB Aquacef-LB" },
    { label: "TAB Aquacef 100 (Cifixim100mg)", value: "TAB Aquacef 100" },
    { label: "TAB Aquazith 250 (Azithromycin)", value: "TAB Aquazith 250" },
    { label: "TAB Aquacilin CV (Amoxycillin Clavulanic Acid625)", value: "TAB Aquacilin CV" },
    { label: "TAB Aquapod-200 (cefpodoxime)", value: "TAB Aquapod-200" },
    { label: "TAB Aquapod-100 (cefpodoxim)", value: "TAB Aquapod-100" },
    { label: "CAP Neuromik-P (Pregabalin & methylcobalamin)", value: "CAP Neuromik-P" },
    { label: "TAB Bizmik-XT (Ferrous Bis-glycinate,zinc bis-glycinate, Folic acid & Methylcobalamin)", value: "TAB Bizmik-XT" },
    { label: "TAB Mifine-D (Mefenamic Acid & Dicylomine Hydrochloride)", value: "TAB Mifine-D" },
    { label: "Syrup Aquacuf-LS (Levosalbutamol, Guailphenesin & Ambroxol HCL syrup)", value: "Syrup Aquacuf-LS" },
    { label: "Syrup Eurocuf-M (Ambroxol 15mg terbutalin sulphate haipensine methol)", value: "Syrup Eurocuf-M" },
    { label: "GEL Arnec-Plus (Diclotenac Diethylaqmine, Linseed Oil, Methyl Salicylate & Menthol)", value: "GEL Arnec-Plus" },
    { label: "Cream LULITEL (Luliconazole Cream)", value: "Cream LULITEL" },
    { label: "Ointment POVIMET (Povidone-iodine, Metronidazole & Aloe ointment)", value: "Ointment POVIMET" },
    { label: "Cream ITRASCOT-PLUS (Itraconazole, Ofloxacin, Ornidazole & Clobetasol Propionate)", value: "Cream ITRASCOT-PLUS" },
    { label: "CAP AQUA-NIGHT (Sildenafil citrate Soft gelatin)", value: "CAP AQUA-NIGHT" },
  ];
  
  export default medicineOptions;
  